(list most-positive-short-float 
      least-positive-short-float 
      least-positive-normalized-short-float 
      most-positive-double-float 
      least-positive-double-float 
      least-positive-normalized-double-float 
      most-positive-long-float 
      least-positive-long-float 
      least-positive-normalized-long-float 
      most-positive-single-float 
      least-positive-single-float 
      least-positive-normalized-single-float 
      most-negative-short-float 
      least-negative-short-float 
      least-negative-normalized-short-float 
      most-negative-single-float 
      least-negative-single-float 
      least-negative-normalized-single-float 
      most-negative-double-float 
      least-negative-double-float 
      least-negative-normalized-double-float 
      most-negative-long-float 
      least-negative-long-float 
      least-negative-normalized-long-float)
