(SETF CLIM-CLX::*CLX-TEXT-FAMILY+FACE-MAP*
        (CLIM-USER::UPDATE-MAP-FOR-FACE-WITH-NAME
         CLIM-CLX::*CLX-TEXT-FAMILY+FACE-MAP* :SERIF
         *DEFAULT-FONT-FAMILY-NAME*))

(MEDIUM-TEXT-STYLE
 (SHEET-MEDIUM (GET-FRAME-PANE *APPLICATION-FRAME* 'CLIM-LISTENER::INTERACTOR)))
